/**
 * Livewatch API
 * Livewatch Server Monitoring API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * Get your free server monitoring token at https://www.livewatch.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['LivewatchApi/ApiClient', 'LivewatchApi/model/MonitoringIp'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/MonitoringIp'));
  } else {
    // Browser globals (root is window)
    if (!root.LivewatchApi) {
      root.LivewatchApi = {};
    }
    root.LivewatchApi.GeneralApi = factory(root.LivewatchApi.ApiClient, root.LivewatchApi.MonitoringIp);
  }
}(this, function(ApiClient, MonitoringIp) {
  'use strict';

  /**
   * General service.
   * @module LivewatchApi/api/GeneralApi
   * @version 1.0.5
   */

  /**
   * Constructs a new GeneralApi. 
   * @alias module:LivewatchApi/api/GeneralApi
   * @class
   * @param {module:LivewatchApi/ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:LivewatchApi/ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the listMonitoringIPs operation.
     * @callback module:LivewatchApi/api/GeneralApi~listMonitoringIPsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:LivewatchApi/model/MonitoringIp>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all our IPs with details
     * Retrieve a list of all IPs (satellite systems) used by Livewatch
     * @param {module:LivewatchApi/api/GeneralApi~listMonitoringIPsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:LivewatchApi/model/MonitoringIp>}
     */
    this.listMonitoringIPs = function(callback) {
      var postBody = null;

      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['LivewatchToken'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [MonitoringIp];
      return this.apiClient.callApi(
        '/api/general/listMonitoringIPs', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }
  };

  return exports;
}));
