/**
 * Livewatch API
 * Livewatch Server Monitoring API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['LivewatchApi/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LivewatchApi) {
      root.LivewatchApi = {};
    }
    root.LivewatchApi.Account = factory(root.LivewatchApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The Account model module.
   * @module LivewatchApi/model/Account
   * @version 1.0.2
   */

  /**
   * Constructs a new <code>Account</code>.
   * @alias module:LivewatchApi/model/Account
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Account</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:LivewatchApi/model/Account} obj Optional instance to populate.
   * @return {module:LivewatchApi/model/Account} The populated <code>Account</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('uuid')) {
        obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
      }
      if (data.hasOwnProperty('credit')) {
        obj['credit'] = ApiClient.convertToType(data['credit'], 'Number');
      }
      if (data.hasOwnProperty('credit_warn_limit')) {
        obj['credit_warn_limit'] = ApiClient.convertToType(data['credit_warn_limit'], 'Number');
      }
      if (data.hasOwnProperty('notification_enabled')) {
        obj['notification_enabled'] = ApiClient.convertToType(data['notification_enabled'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} uuid
   */
  exports.prototype['uuid'] = undefined;
  /**
   * @member {Number} credit
   */
  exports.prototype['credit'] = undefined;
  /**
   * @member {Number} credit_warn_limit
   */
  exports.prototype['credit_warn_limit'] = undefined;
  /**
   * @member {Boolean} notification_enabled
   */
  exports.prototype['notification_enabled'] = undefined;



  return exports;
}));


