/**
 * Livewatch API
 * Livewatch Server Monitoring API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * Get your free server monitoring token at https://www.livewatch.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['LivewatchApi/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LivewatchApi) {
      root.LivewatchApi = {};
    }
    root.LivewatchApi.CheckStats = factory(root.LivewatchApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The CheckStats model module.
   * @module LivewatchApi/model/CheckStats
   * @version 1.0.8
   */

  /**
   * Constructs a new <code>CheckStats</code>.
   * @alias module:LivewatchApi/model/CheckStats
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>CheckStats</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:LivewatchApi/model/CheckStats} obj Optional instance to populate.
   * @return {module:LivewatchApi/model/CheckStats} The populated <code>CheckStats</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'String');
      }
      if (data.hasOwnProperty('unknown')) {
        obj['unknown'] = ApiClient.convertToType(data['unknown'], 'Number');
      }
      if (data.hasOwnProperty('ok')) {
        obj['ok'] = ApiClient.convertToType(data['ok'], 'Number');
      }
      if (data.hasOwnProperty('warning')) {
        obj['warning'] = ApiClient.convertToType(data['warning'], 'Number');
      }
      if (data.hasOwnProperty('critical')) {
        obj['critical'] = ApiClient.convertToType(data['critical'], 'Number');
      }
      if (data.hasOwnProperty('total')) {
        obj['total'] = ApiClient.convertToType(data['total'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} date
   */
  exports.prototype['date'] = undefined;
  /**
   * @member {Number} unknown
   */
  exports.prototype['unknown'] = undefined;
  /**
   * @member {Number} ok
   */
  exports.prototype['ok'] = undefined;
  /**
   * @member {Number} warning
   */
  exports.prototype['warning'] = undefined;
  /**
   * @member {Number} critical
   */
  exports.prototype['critical'] = undefined;
  /**
   * @member {Number} total
   */
  exports.prototype['total'] = undefined;



  return exports;
}));


