/**
 * Livewatch API
 * Livewatch Server Monitoring API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * Get your free server monitoring token at https://www.livewatch.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 6.2.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['LivewatchApi/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LivewatchApi) {
      root.LivewatchApi = {};
    }
    root.LivewatchApi.CheckNotification = factory(root.LivewatchApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The CheckNotification model module.
   * @module LivewatchApi/model/CheckNotification
   * @version 1.1.2
   */

  /**
   * Constructs a new <code>CheckNotification</code>.
   * @alias module:LivewatchApi/model/CheckNotification
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>CheckNotification</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:LivewatchApi/model/CheckNotification} obj Optional instance to populate.
   * @return {module:LivewatchApi/model/CheckNotification} The populated <code>CheckNotification</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('uuid')) {
        obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('notification')) {
        obj['notification'] = ApiClient.convertToType(data['notification'], 'String');
      }
      if (data.hasOwnProperty('contact_name')) {
        obj['contact_name'] = ApiClient.convertToType(data['contact_name'], 'String');
      }
      if (data.hasOwnProperty('check_name')) {
        obj['check_name'] = ApiClient.convertToType(data['check_name'], 'String');
      }
      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'Number');
      }
      if (data.hasOwnProperty('contactName')) {
        obj['contactName'] = ApiClient.convertToType(data['contactName'], 'String');
      }
      if (data.hasOwnProperty('checkName')) {
        obj['checkName'] = ApiClient.convertToType(data['checkName'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} uuid
   */
  exports.prototype['uuid'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} notification
   */
  exports.prototype['notification'] = undefined;
  /**
   * @member {String} contact_name
   */
  exports.prototype['contact_name'] = undefined;
  /**
   * @member {String} check_name
   */
  exports.prototype['check_name'] = undefined;
  /**
   * @member {String} date
   */
  exports.prototype['date'] = undefined;
  /**
   * @member {Number} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {String} contactName
   */
  exports.prototype['contactName'] = undefined;
  /**
   * @member {String} checkName
   */
  exports.prototype['checkName'] = undefined;



  return exports;
}));


