/**
 * Livewatch API
 * Livewatch Server Monitoring API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * Get your free server monitoring token at https://www.livewatch.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 6.2.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/LivewatchApi/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/LivewatchApi/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LivewatchApi);
  }
}(this, function(expect, LivewatchApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    // create a new instance
    //instance = new LivewatchApi.CheckHistory();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CheckHistory', function() {
    it('should create an instance of CheckHistory', function() {
      // uncomment below and update the code to test CheckHistory
      //var instance = new LivewatchApi.CheckHistory();
      //expect(instance).to.be.a(LivewatchApi.CheckHistory);
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instance = new LivewatchApi.CheckHistory();
      //expect(instance).to.be();
    });

    it('should have the property checkType (base name: "checkType")', function() {
      // uncomment below and update the code to test the property checkType
      //var instance = new LivewatchApi.CheckHistory();
      //expect(instance).to.be();
    });

    it('should have the property performedAt (base name: "performedAt")', function() {
      // uncomment below and update the code to test the property performedAt
      //var instance = new LivewatchApi.CheckHistory();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new LivewatchApi.CheckHistory();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instance = new LivewatchApi.CheckHistory();
      //expect(instance).to.be();
    });

  });

}));
